name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
  workflow_dispatch:
  create:
    tags:
      - '*'

jobs:
  build:
    strategy:
      matrix:
        python-version: [3.8, 3.11, 3.12]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run tests
        run: python -m unittest discover -s src/test

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: pip install flake8 bandit
      - name: Linting and Security
        run: |
          pip install -r requirements.txt
          pip install flake8 bandit

  release:
    needs: [build, lint]
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Generate Changelog
        run: |
          git log $(git describe --tags --abbrev=0)..HEAD --pretty=format:"- %s" > CHANGELOG.md
      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          body: |
            $(cat CHANGELOG.md)
          artifacts: "dist/*"

  docs:
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: pip install mkdocs
      - name: Build and Deploy Docs
        run: |
          mkdocs build
          mkdocs gh-deploy --force
